# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\")\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\"O\n\rQueryResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x0f\n\x07latency\x18\x03 \x01(\x02\x12\x11\n\tworker_id\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"R\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x17\n\x0f\x61\x63tive_requests\x18\x02 \x01(\x05\x12\x16\n\x0e\x61vg_latency_ms\x18\x03 \x01(\x02\x32\x85\x01\n\rWorkerService\x12\x36\n\x07Process\x12\x14.worker.QueryRequest\x1a\x15.worker.QueryResponse\x12<\n\x0bHealthCheck\x12\x15.worker.HealthRequest\x1a\x16.worker.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=24
  _globals['_QUERYREQUEST']._serialized_end=65
  _globals['_QUERYRESPONSE']._serialized_start=67
  _globals['_QUERYRESPONSE']._serialized_end=146
  _globals['_HEALTHREQUEST']._serialized_start=148
  _globals['_HEALTHREQUEST']._serialized_end=163
  _globals['_HEALTHRESPONSE']._serialized_start=165
  _globals['_HEALTHRESPONSE']._serialized_end=247
  _globals['_WORKERSERVICE']._serialized_start=250
  _globals['_WORKERSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
